<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildProjectDirectory)\bin\**;$(MSBuildProjectDirectory)\obj\**;**\._*;**\.DS_Store</DefaultItemExcludes>
    <AssemblyName>MajdataLauncher</AssemblyName>
    <RootNamespace>MajdataLauncher</RootNamespace>
    <ApplicationIcon>..\MajdataEdit\bear-3.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Pets\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
